// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjp1WeIbXQu38py_UImYIlmLCcAfDzDpA',
    appId: '1:475894856483:web:af7632212d485507fa6a96',
    messagingSenderId: '475894856483',
    projectId: 'campuscanteen-7d800',
    authDomain: 'campuscanteen-7d800.firebaseapp.com',
    storageBucket: 'campuscanteen-7d800.firebasestorage.app',
    databaseURL: 'https://campuscanteen-7d800-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC3Nq7NDx0QA9mYyYYFzKVkTdX8jWVhuw',
    appId: '1:475894856483:android:4a248d0b5734e3b0fa6a96',
    messagingSenderId: '475894856483',
    projectId: 'campuscanteen-7d800',
    storageBucket: 'campuscanteen-7d800.firebasestorage.app',
    databaseURL: 'https://campuscanteen-7d800-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
